### ISSUE TITLE
time data does not match

### ISSUE THREAD

**Issue by benb0jangles** [PaulMcInnis/JobFunnel#143]
Command:
`funnel load -s my_settings.yaml`

Brings Error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/funnel", line 11, in <module>
    load_entry_point('JobFunnel==3.0.2', 'console_scripts', 'funnel')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jobfunnel/__main__.py", line 28, in main
    job_funnel.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jobfunnel/backend/jobfunnel.py", line 86, in run
    self.master_jobs_dict = self.read_master_csv()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jobfunnel/backend/jobfunnel.py", line 367, in read_master_csv
    post_date = datetime.strptime(row['date'], '%Y-%m-%d')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '13/04/2021' does not match format '%Y-%m-%d'
```

**Comment by benb0jangles** [comment]
Ok, I just deleted all previous files in folder:
`demo_job_search_results`

**Comment by theschles** [comment]
A note to all: if you open the generated CSV in Excel, it will automatically change the `date` column into `MM/DD/YY` format -- and this script expects the date to be in `YYYY-MM-DD` format.

So: if you use Excel to edit the generated CSV, each time open the CSV, you need to:
1. Select all cells in the `date` column
2. Right-click on the highlighted cells and choose "Format Cells"
3. Within the Format Cells dialog, select `2012-03-14` value and click the OK button
4. Give the list 15 to 30 seconds for it to adjust the cells.
